#INIT FILE

#REQUIRED FOR IDENTIFICATION OF OTHER SCRIPTS IN ROOT FOLDER

#FILES CONTAINED:
#	1. Main.py : BASE FILE FOR HANDLING AND SENDING DATA
#	2. send_mail.py : CLASS FOR STARTING SIMPLE SMTP CLIENT AND SENDING MAIL TO ANY MAIL ID
#	3. db_content.py : CLASSES FOR HANDLING SQLITE DATABASE OPERATIONS AND FOR CREATING STRUCTURE OF NOTE CONTENTS.